/*
 * Ravimoshark Contract API
 * This is an API to interact with Ravimoshark contracts database. # Introduction This API allow to create, modify and delete contracts and machines. It also interacts with machines imported from SAGE database. # User Authentication This API does not contain any kind of user validation but It request to have a valid authentication user to interact with it. For more information about user Authentication, please refer to [Ravimoshark User Authentication](https://ravimoshark.com/back/apis/auth/latest). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ravimoshark.apis.task.calls;

import com.ravimoshark.apis.task.ApiException;
import com.ravimoshark.apis.task.model.CustomError;
import com.ravimoshark.apis.task.model.Deleted;
import com.ravimoshark.apis.task.model.IdInteger;
import com.ravimoshark.apis.task.model.ImportedMachines;
import com.ravimoshark.apis.task.model.InlineResponse2002;
import com.ravimoshark.apis.task.model.Machines;
import com.ravimoshark.apis.task.model.Reviewed;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ImportedMachinesApi
 */
@Ignore
public class ImportedMachinesApiTest {

    private final ImportedMachinesApi api = new ImportedMachinesApi();

    /**
     * Add one imported Machine.
     *
     * Add one imported Machine.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addImportedMachineTest() throws ApiException {
        ImportedMachines body = null;
        ImportedMachines response = api.addImportedMachine(body);

        // TODO: test validations
    }
    /**
     * Delete one imported Machine.
     *
     * Delete one imported Machine.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteImportedMachineTest() throws ApiException {
        Long id = null;
        IdInteger response = api.deleteImportedMachine(id);

        // TODO: test validations
    }
    /**
     * Edit one imported Machine.
     *
     * Edit one imported Machine.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void editImportedMachineTest() throws ApiException {
        ImportedMachines body = null;
        ImportedMachines response = api.editImportedMachine(body);

        // TODO: test validations
    }
    /**
     * Get one imported Machine.
     *
     * Get one imported Machine.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getImportedMachineByIdTest() throws ApiException {
        Long id = null;
        Deleted deleted = null;
        Machines response = api.getImportedMachineById(id, deleted);

        // TODO: test validations
    }
    /**
     * Get all imported Machines.
     *
     * Get all imported Machines.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getImportedMachinesTest() throws ApiException {
        Integer skip = null;
        Integer limit = null;
        String orderBy = null;
        String filterBy = null;
        Deleted deleted = null;
        Boolean metadata = null;
        Reviewed reviewed = null;
        String refClient = null;
        Long refContract = null;
        InlineResponse2002 response = api.getImportedMachines(skip, limit, orderBy, filterBy, deleted, metadata, reviewed, refClient, refContract);

        // TODO: test validations
    }
}
