/*
 * Ravimoshark Contract API
 * This is an API to interact with Ravimoshark contracts database. # Introduction This API allow to create, modify and delete contracts and machines. It also interacts with machines imported from SAGE database. # User Authentication This API does not contain any kind of user validation but It request to have a valid authentication user to interact with it. For more information about user Authentication, please refer to [Ravimoshark User Authentication](https://ravimoshark.com/back/apis/auth/latest). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ravimoshark.apis.task.calls;

import com.ravimoshark.apis.task.ApiException;
import com.ravimoshark.apis.task.model.CustomError;
import com.ravimoshark.apis.task.model.Deleted;
import com.ravimoshark.apis.task.model.IdInteger;
import com.ravimoshark.apis.task.model.InlineResponse2004;
import com.ravimoshark.apis.task.model.Machines;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MachinesApi
 */
@Ignore
public class MachinesApiTest {

    private final MachinesApi api = new MachinesApi();

    /**
     * Add one machine.
     *
     * Add one machine.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addMachineTest() throws ApiException {
        Machines body = null;
        Machines response = api.addMachine(body);

        // TODO: test validations
    }
    /**
     * Delete one machine.
     *
     * Delete one machine.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteMachineTest() throws ApiException {
        Long id = null;
        IdInteger response = api.deleteMachine(id);

        // TODO: test validations
    }
    /**
     * Edit one machine.
     *
     * Edit one machine.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void editMachineTest() throws ApiException {
        Machines body = null;
        Machines response = api.editMachine(body);

        // TODO: test validations
    }
    /**
     * Get one Machine.
     *
     * Get one machine.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMachineByIdTest() throws ApiException {
        Long id = null;
        Deleted deleted = null;
        Machines response = api.getMachineById(id, deleted);

        // TODO: test validations
    }
    /**
     * Get all machines.
     *
     * Get all machines.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMachinesTest() throws ApiException {
        Integer skip = null;
        Integer limit = null;
        String orderBy = null;
        String filterBy = null;
        Deleted deleted = null;
        Boolean metadata = null;
        String refClient = null;
        Long refContract = null;
        InlineResponse2004 response = api.getMachines(skip, limit, orderBy, filterBy, deleted, metadata, refClient, refContract);

        // TODO: test validations
    }
}
