/*
 * Ravimoshark Task API
 * This is an API to interact with Ravimoshark task database. # Introduction This API allow to create, modify and delete task, visits, technicians and interventions. # User Authentication This API does not contain any kind of user validation but It request to have a valid authentication user to interact with it. For more information about user Authentication, please refer to [Ravimoshark User Authentication](https://ravimoshark.com/back/apis/auth/latest). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ravimoshark.apis.task.calls;

import com.ravimoshark.apis.task.ApiException;
import com.ravimoshark.apis.task.model.CustomError;
import com.ravimoshark.apis.task.model.Deleted;
import com.ravimoshark.apis.task.model.IdInteger;
import com.ravimoshark.apis.task.model.InlineResponse2003;
import com.ravimoshark.apis.task.model.Visits;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VisitsApi
 */
@Ignore
public class VisitsApiTest {

    private final VisitsApi api = new VisitsApi();

    /**
     * Add one visit.
     *
     * Add one visit.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addVisitTest() throws ApiException {
        Visits body = null;
        Visits response = api.addVisit(body);

        // TODO: test validations
    }
    /**
     * Delete one visit.
     *
     * Delete one visit.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteVisitTest() throws ApiException {
        Long id = null;
        IdInteger response = api.deleteVisit(id);

        // TODO: test validations
    }
    /**
     * Edit one visit.
     *
     * Edit one visit.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void editVisitTest() throws ApiException {
        Visits body = null;
        Visits response = api.editVisit(body);

        // TODO: test validations
    }
    /**
     * Get one visit.
     *
     * Get one visit.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getVisitByIdTest() throws ApiException {
        Long id = null;
        Deleted deleted = null;
        Visits response = api.getVisitById(id, deleted);

        // TODO: test validations
    }
    /**
     * Get all visits.
     *
     * Get all visits.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getVisitsTest() throws ApiException {
        Integer skip = null;
        Integer limit = null;
        String orderBy = null;
        String filterBy = null;
        Deleted deleted = null;
        Boolean metadata = null;
        String refClient = null;
        String technicianId = null;
        InlineResponse2003 response = api.getVisits(skip, limit, orderBy, filterBy, deleted, metadata, refClient, technicianId);

        // TODO: test validations
    }
}
